package com.mobilerpgpack.phone.engine.engineinfo.doombfa

import com.mobilerpgpack.phone.engine.engineinfo.doombfa.DoomBFAEngineInfo.Companion.DEFAULT_SHADOW_IMAGE_MAP_SIZE
import com.mobilerpgpack.phone.engine.engineinfo.fteqw.FTEQWGames
import com.mobilerpgpack.phone.utils.PreferencesStorage
import com.mobilerpgpack.phone.utils.sharesprefs.booleanPreferencesKey
import com.mobilerpgpack.phone.utils.sharesprefs.enumPreferencesKey
import com.mobilerpgpack.phone.utils.sharesprefs.intPreferencesKey
import com.mobilerpgpack.phone.utils.sharesprefs.stringPreferencesKey

class DoomBFAPreferencesStorage : PreferencesStorage() {
    val pathToDoom3ResourcesPreferenceKey = stringPreferencesKey("path_to_doom3_resources")
    val commandLineArgsPrefsKey = stringPreferencesKey("doom3_command_line_args")
    val disablePostProcessEffectsPrefsKey = booleanPreferencesKey("disable_postprocess_effects")
    val disableParticlesPrefsKey = booleanPreferencesKey("disable_particles")
    val disableNewAmbientsPrefsKey = booleanPreferencesKey("disable_bfg_new_ambients")
    val disableBlendLightsPrefsKey = booleanPreferencesKey("disable_blend_lights")
    val disableDynamicTexturesPrefsKey = booleanPreferencesKey("disable_dynamic_textures")
    val disableCopyTexturesPrefsKey = booleanPreferencesKey("disable_copy_textures")
    val skipDeformsPrefsKey = booleanPreferencesKey("skip_deforms")
    val useShadowMappingPrefsKey = booleanPreferencesKey("use_shadow_mapping")
    val disableOverlaysPrefsKey = booleanPreferencesKey("disable_overlays")
    val useLightDepthBoundsPrefsKey = booleanPreferencesKey("use_lights_depth_bounds")
    val disableIntelWorkaroundsPrefsKey = booleanPreferencesKey("disable_all_intel_workarounds")
    val useShadowDepthBoundsPrefsKey = booleanPreferencesKey("use_shadows_depth_bounds")
    val disablePrelightShadowsPrefsKey = booleanPreferencesKey("disable_prelight_shadows")
    val enableDXTHardwareSupportPrefsKey = booleanPreferencesKey("enable_dxt_hardware_support")
    val disableShadowsPrefsKey = booleanPreferencesKey("disable_shadows")
    val disableTranslucentPrefsKey = booleanPreferencesKey("disable_translucent")
    val disableFogLightsPrefsKey = booleanPreferencesKey("disable_fog_lights")
    val disableSpecularPrefsKey = booleanPreferencesKey("disable_specular")
    val disableLightInteractionsPrefsKey = booleanPreferencesKey("disable_light_interactions")
    val simplifyCullingPrefsKey = booleanPreferencesKey("simplify_culling")
    val enableDoom3ModsPrefsKey = booleanPreferencesKey("enable_doom3_mods")
    val pathDoom3ModsDirPrefsKey = stringPreferencesKey("path_to_doom3_mods_dir")
    val shadowMapImageSizePrefsKey = stringPreferencesKey("shadow_map_image_size")
    val targetGLESVersionPrefsKey = enumPreferencesKey<GLESVersions>("target_gles_version")
    val disableStaticShadowsPrefsKey = booleanPreferencesKey("disable_static_shadows")
    val disableDynamicShadowsPrefsKey = booleanPreferencesKey("disable_dynamic_shadows")
    val useShadowPreciseInsideTestPrefsKey = booleanPreferencesKey("use_shadows_precise_inside_tests")
    val lodDistancePrefsKey = intPreferencesKey("lod_distance")
    val enableTexturesShrinkingPrefsKey = booleanPreferencesKey("enable_textures_shrinking")
    val enableETC2TextureCachePrefsKey = booleanPreferencesKey("enable_etc2_doom3_texture_cache")
    val enableGLSynchronizationPrefsKey = booleanPreferencesKey("enable_gl_syncronizations")

    val enableGLSynchronization = getBooleanValue(enableGLSynchronizationPrefsKey,false)
    val enableETC2TextureCache = getBooleanValue(enableETC2TextureCachePrefsKey, true)
    val enableTexturesShrinking = getBooleanValue(enableTexturesShrinkingPrefsKey)
    val disableStaticShadows = getBooleanValue(disableStaticShadowsPrefsKey)
    val disableDynamicShadows = getBooleanValue(disableDynamicShadowsPrefsKey)
    val useShadowPreciseInsideTest = getBooleanValue(useShadowPreciseInsideTestPrefsKey, false)
    val lodDistance = getIntValue(lodDistancePrefsKey, 500)
    val commandLineArgs = getStringValue(commandLineArgsPrefsKey)
    val targetGLESVersion = getEnumValue(targetGLESVersionPrefsKey, GLESVersions::class.java,
        GLESVersions.defaultGLESVersion)
    val pathToDoom3Resources = getStringValue(pathToDoom3ResourcesPreferenceKey)
    val shadowMapImageSize = getStringValue(shadowMapImageSizePrefsKey, DEFAULT_SHADOW_IMAGE_MAP_SIZE)
    val pathDoom3ModsDir = getStringValue(pathDoom3ModsDirPrefsKey)
    val enableDoom3Mods = getBooleanValue(enableDoom3ModsPrefsKey)
    val simplifyCulling = getBooleanValue(simplifyCullingPrefsKey)
    val disableFogLights = getBooleanValue(disableFogLightsPrefsKey)
    val disableTranslucent = getBooleanValue(disableTranslucentPrefsKey)
    val disablePostProcessEffects= getBooleanValue(disablePostProcessEffectsPrefsKey,false)
    val disableShadows = getBooleanValue(disableShadowsPrefsKey)
    val disableParticles = getBooleanValue(disableParticlesPrefsKey)
    val disableSpecular = getBooleanValue(disableSpecularPrefsKey)
    val disableLightInteractions = getBooleanValue(disableLightInteractionsPrefsKey)
    val disableNewAmbients= getBooleanValue(disableNewAmbientsPrefsKey)
    val disableBlendLights = getBooleanValue(disableBlendLightsPrefsKey)
    val disableDynamicTextures = getBooleanValue(disableDynamicTexturesPrefsKey)
    val disableCopyTextures= getBooleanValue(disableCopyTexturesPrefsKey)
    val skipDeforms = getBooleanValue(skipDeformsPrefsKey)
    val useShadowMapping = getBooleanValue(useShadowMappingPrefsKey,false)
    val disableOverlays = getBooleanValue(disableOverlaysPrefsKey)
    val useLightDepthBounds = getBooleanValue(useLightDepthBoundsPrefsKey,false)
    val disableIntelWorkarounds = getBooleanValue(disableIntelWorkaroundsPrefsKey,true)
    val useShadowDepthBounds = getBooleanValue(useShadowDepthBoundsPrefsKey,false)
    val disablePrelightShadows = getBooleanValue(disablePrelightShadowsPrefsKey,false)
    val enableDXTHardwareSupport = getBooleanValue(enableDXTHardwareSupportPrefsKey,true)
}