// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    ext.versions = [
            app_package_name : "com.mobilerpgpack.phone",
            app_version_code : 105,
            app_version_name : "3.1.8",
            min_sdk : 26,
            target_sdk : 37,
            target_sdk_min_revision : 0,
            ndk_version : '29.0.14206865',
            build_tools_version : '37.0.0',
            native_android_platform_version : 26,
            cmake_version : "4.1.2"
    ]
    ext.build_flags = [
            compiling_arguments : "-j${Runtime.getRuntime().availableProcessors()}",
            common_c_flags : ["-Os","-flto=thin", "-fno-omit-frame-pointer","-funwind-tables","-fstack-protector-strong",
                              "-g", "-D_FILE_OFFSET_BITS=64"],
            common_cpp_flags : ["-Os" ,"-flto=thin", "-fno-omit-frame-pointer","-funwind-tables","-fstack-protector-strong",
                                "-g", "-D_FILE_OFFSET_BITS=64"],
            ndk_build_flags : "APP_LDFLAGS=-fuse-ld=lld -flto=thin -Wl,--build-id",
            ndk_build_android_stl : "APP_STL=c++_shared",
            CMAKE_CFLAGS : "-Os -flto=thin -fno-omit-frame-pointer -funwind-tables -fstack-protector-strong -g -D_FILE_OFFSET_BITS=64",
            CMAKE_CXXFLAGS : "-Os -flto=thin -fno-omit-frame-pointer -funwind-tables -fstack-protector-strong -g -D_FILE_OFFSET_BITS=64",
            CMAKE_ANDROID_STL : "-DANDROID_STL=c++_shared",
            CMAKE_SHADERLINKER_FLAGS :"-flto=thin -fuse-ld=lld -Wl,--build-id",
            ndk_build_platform : "APP_PLATFORM=android-${versions.native_android_platform_version}"
    ]
    ext.rootDir = rootProject.rootDir
    repositories {
        google()
    }
    dependencies {
        classpath libs.google.services
        classpath(libs.kotlin.gradle.plugin)
    }
}


plugins {
alias(libs.plugins.android.application) apply false
    alias(libs.plugins.android.library) apply false
}