pluginManagement {
    repositories {
        google {
            content {
                includeGroupByRegex("com\\.android.*")
                includeGroupByRegex("com\\.google.*")
                includeGroupByRegex("androidx.*")
            }
        }
        mavenCentral()
        gradlePluginPortal()
    }
}
plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "Classic Core"
include ':app'
include ':third_party:openal'
include ':third_party:sdl3:android-project:app'
include ':third_party:fluidsynth'
include ':third_party:CTranslate2'
include ':third_party:sentencepiece'
include ':machine_translator:CTranslate2Proxy'
include ':third_party:NG-GL4ES'
include ':third_party:libpng'
include ':third_party:storage-chooser:storagechooser'
include ':third_party:legacy_gl4es'
include ':third_party:bing_translator'
include ':third_party:oboe'
include ':third_party:freetype'
include ':third_party:zmusic'
include ':third_party:mpg123'
include ':third_party:libsndfile'
include ':third_party:flac'
include ':third_party:libvorbis'
include ':third_party:opus'
include ':third_party:libmp3lame'
include ':third_party:libjpegturbo'
include ':third_party:bzip2'
include ':third_party:ogg'
include ':third_party:angle'
include ':third_party:sdl2-compat'
