import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.android.library)
}

kotlin {
    compilerOptions {
        jvmTarget.set(JvmTarget.JVM_17)
    }
}

android {
    namespace 'com.mobilerpgpack.ctranslate2proxy'
    compileSdk {
        version = release(versions.target_sdk) {
            minorApiLevel = versions.target_sdk_min_revision
        }
    }

    defaultConfig {
        minSdk versions.min_sdk
        targetSdk versions.target_sdk

        ndk {
            abiFilters = abi_filters
        }
        externalNativeBuild {
            cmake {
                arguments "-DANDROID_PLATFORM=android-$versions.native_android_platform_version",
                        "-DCMAKE_CXX_FLAGS=$build_flags.CMAKE_CXXFLAGS",
                        "-DCMAKE_C_FLAGS=$build_flags.CMAKE_CFLAGS",
                        "-DCMAKE_C_COMPILER_LAUNCHER=ccache", "-DCMAKE_CXX_COMPILER_LAUNCHER=ccache",
                        "-DCMAKE_SHARED_LINKER_FLAGS=$build_flags.CMAKE_SHADERLINKER_FLAGS",
                        "$build_flags.CMAKE_ANDROID_STL","-DANDROID_ARM_MODE=arm","-D_FILE_OFFSET_BITS=64"
            }
        }
    }
    externalNativeBuild {
        cmake {
            path "CMakeLists.txt"
            version versions.cmake_version
        }
    }
    buildTypes {
        release {
            externalNativeBuild {
                cmake {
                    arguments "-DCMAKE_BUILD_TYPE=MinSizeRel"
                }
            }
            ndk {
                debugSymbolLevel 'FULL'
            }
        }
        debug {
            externalNativeBuild {
                cmake {
                    arguments "-DCMAKE_BUILD_TYPE=Debug"
                }
            }
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    buildToolsVersion versions.build_tools_version
    ndkVersion versions.ndk_version
    buildFeatures {
        buildConfig true
    }
}

preBuild.dependsOn ':third_party:CTranslate2:build', ':third_party:sentencepiece:build'

dependencies {
    implementation(libs.icu4j)
    implementation (project(":third_party:CTranslate2"))
    implementation (project(":third_party:sentencepiece"))
    implementation(libs.jna){ artifact { type = "aar" } }
    implementation libs.androidx.core.ktx
    implementation libs.androidx.appcompat
    implementation libs.material
    testImplementation libs.junit
    androidTestImplementation libs.androidx.junit
    androidTestImplementation libs.androidx.espresso.core
}