package com.mobilerpgpack.phone.ui.screen.screencontrols.layout

import android.view.KeyEvent
import com.mobilerpgpack.phone.R
import com.mobilerpgpack.phone.engine.EngineTypes
import com.mobilerpgpack.phone.ui.screen.EnableEditModeButton
import com.mobilerpgpack.phone.ui.screen.screencontrols.ControlsType
import com.mobilerpgpack.phone.ui.screen.screencontrols.IScreenControlsView
import com.mobilerpgpack.phone.ui.screen.screencontrols.UpdateQuickPanelVisibilityImageButton
import com.mobilerpgpack.phone.ui.screen.screencontrols.UpdateScreenControlsVisibilityImageButton
import com.mobilerpgpack.phone.ui.screen.screencontrols.sdl.KeyboardType
import com.mobilerpgpack.phone.ui.screen.screencontrols.sdl.SDLScreenController.Companion.LEFT_MOUSE_BUTTON_ID
import com.mobilerpgpack.phone.ui.screen.screencontrols.sdl.SDLScreenController.Companion.SDL_BUTTON_RIGHT
import com.mobilerpgpack.phone.ui.screen.screencontrols.sdl.ShowSDLKeyboardButton
import com.mobilerpgpack.phone.ui.screen.screencontrols.sdl3.SDL3Dpad
import com.mobilerpgpack.phone.ui.screen.screencontrols.sdl3.SDL3ImageButton
import com.mobilerpgpack.phone.ui.screen.screencontrols.sdl3.SDL3MouseImageButton
import com.mobilerpgpack.phone.ui.screen.screencontrols.sdl3.SDL3MouseWheelButton
import com.mobilerpgpack.phone.ui.screen.screencontrols.sdl3.SDL3OnScreenStick
import com.mobilerpgpack.phone.ui.screen.screencontrols.sdl3.SDL3RadialWheel

val widelandsAbsoluteControlsLayout: Collection<IScreenControlsView> = listOf(
    EnableEditModeButton(
        EngineTypes.Widelands,
        offsetXPercent = 0.015f,
        offsetYPercent = 0.02f,
        sizePercent = 0.055f,
    ),
    SDL3RadialWheel(
        EngineTypes.Widelands,
        offsetXPercent = 0.55f,
        offsetYPercent = 0.28f,
        sizePercent = 0.21f,
        isDeleted = true
    ),
    SDL3Dpad(
        EngineTypes.Widelands,
        offsetXPercent = 0.03f,
        offsetYPercent = 0.16f,
        sizePercent = 0.16f,
    ),
    SDL3MouseImageButton(
        "left_mouse_button",
        EngineTypes.Widelands,
        offsetXPercent = 0.52f,
        offsetYPercent = 0.03f,
        sizePercent = 0.06f,
        buttonResId = R.drawable.mouse,
        sdlKeyEvent = LEFT_MOUSE_BUTTON_ID,
        useToggle = false,
        isDeleted = true
    ),
    UpdateQuickPanelVisibilityImageButton(
        EngineTypes.Widelands,
        offsetXPercent = 0.1f,
        offsetYPercent = 0.03f,
        sizePercent = 0.05f,
        buttonResId = R.drawable.quick_panel,
    ),
    SDL3ImageButton(
        "encyclopedia",
        EngineTypes.Widelands,
        offsetXPercent = 0.16f,
        offsetYPercent = 0.03f,
        sizePercent = 0.05f,
        buttonResId = R.drawable.secret_book,
        sdlKeyEvent = KeyEvent.KEYCODE_F1,
        showInQuickPanel = true,
    ),
    SDL3ImageButton(
        "select_all",
        EngineTypes.Widelands,
        offsetXPercent = 0.22f,
        offsetYPercent = 0.03f,
        sizePercent = 0.05f,
        buttonResId = R.drawable.select_all,
        sdlKeyEvent = KeyEvent.KEYCODE_F4,
        showInQuickPanel = true,
    ),
    SDL3ImageButton(
        "delete_item",
        EngineTypes.Widelands,
        offsetXPercent = 0.28f,
        offsetYPercent = 0.03f,
        sizePercent = 0.05f,
        buttonResId = R.drawable.delete_icon,
        sdlKeyEvent = KeyEvent.KEYCODE_FORWARD_DEL,
        showInQuickPanel = true,
    ),
    SDL3ImageButton(
        "tooltip_accessibility_mode",
        EngineTypes.Widelands,
        offsetXPercent = 0.34f,
        offsetYPercent = 0.03f,
        sizePercent = 0.05f,
        buttonResId = R.drawable.tooltip,
        sdlKeyEvent = KeyEvent.KEYCODE_F2,
        showInQuickPanel = true,
    ),
    SDL3ImageButton(
        "messages",
        EngineTypes.Widelands,
        offsetXPercent = 0.40f,
        offsetYPercent = 0.03f,
        sizePercent = 0.05f,
        buttonResId = R.drawable.nothing_to_say,
        sdlKeyEvent = KeyEvent.KEYCODE_N,
        showInQuickPanel = true,
    ),
    SDL3ImageButton(
        "objectives",
        EngineTypes.Widelands,
        offsetXPercent = 0.46f,
        offsetYPercent = 0.03f,
        sizePercent = 0.05f,
        buttonResId = R.drawable.objectives,
        sdlKeyEvent = KeyEvent.KEYCODE_T,
        showInQuickPanel = true,
    ),
    SDL3ImageButton(
        "diplomacy",
        EngineTypes.Widelands,
        offsetXPercent = 0.16f,
        offsetYPercent = 0.15f,
        sizePercent = 0.05f,
        buttonResId = R.drawable.diploma,
        sdlKeyEvent = KeyEvent.KEYCODE_D,
        showInQuickPanel = true,
    ),
    SDL3ImageButton(
        "game_chat",
        EngineTypes.Widelands,
        offsetXPercent = 0.22f,
        offsetYPercent = 0.15f,
        sizePercent = 0.05f,
        buttonResId = R.drawable.chat,
        sdlKeyEvent = KeyEvent.KEYCODE_ENTER,
        showInQuickPanel = true,
    ),
    SDL3ImageButton(
        "general_statistics",
        EngineTypes.Widelands,
        offsetXPercent = 0.28f,
        offsetYPercent = 0.15f,
        sizePercent = 0.05f,
        buttonResId = R.drawable.analytics,
        sdlKeyEvent = KeyEvent.KEYCODE_A,
        showInQuickPanel = true,
    ),
    SDL3ImageButton(
        "ware_statistics",
        EngineTypes.Widelands,
        offsetXPercent = 0.34f,
        offsetYPercent = 0.15f,
        sizePercent = 0.05f,
        buttonResId = R.drawable.warehouse,
        sdlKeyEvent = KeyEvent.KEYCODE_P,
        showInQuickPanel = true,
    ),
    SDL3ImageButton(
        "building_statistics",
        EngineTypes.Widelands,
        offsetXPercent = 0.40f,
        offsetYPercent = 0.15f,
        sizePercent = 0.05f,
        buttonResId = R.drawable.village,
        sdlKeyEvent = KeyEvent.KEYCODE_B,
        showInQuickPanel = true,
    ),
    SDL3ImageButton(
        "soldier_statistics",
        EngineTypes.Widelands,
        offsetXPercent = 0.22f,
        offsetYPercent = 0.27f,
        sizePercent = 0.05f,
        buttonResId = R.drawable.guards,
        sdlKeyEvent = KeyEvent.KEYCODE_X,
        showInQuickPanel = true,
    ),
    SDL3ImageButton(
        "seafaring_statistics",
        EngineTypes.Widelands,
        offsetXPercent = 0.28f,
        offsetYPercent = 0.27f,
        sizePercent = 0.05f,
        buttonResId = R.drawable.at_sea,
        sdlKeyEvent = KeyEvent.KEYCODE_E,
        showInQuickPanel = true,
    ),
    SDL3ImageButton(
        "toggle_census",
        EngineTypes.Widelands,
        offsetXPercent = 0.34f,
        offsetYPercent = 0.27f,
        sizePercent = 0.05f,
        buttonResId = R.drawable.folded_paper,
        sdlKeyEvent = KeyEvent.KEYCODE_C,
        showInQuickPanel = true,
    ),
    SDL3ImageButton(
        "toggle_status_labels",
        EngineTypes.Widelands,
        offsetXPercent = 0.40f,
        offsetYPercent = 0.27f,
        sizePercent = 0.05f,
        buttonResId = R.drawable.cloud_alert,
        sdlKeyEvent = KeyEvent.KEYCODE_S,
        showInQuickPanel = true,
    ),
    SDL3ImageButton(
        "toggle_soldier_levels",
        EngineTypes.Widelands,
        offsetXPercent = 0.22f,
        offsetYPercent = 0.39f,
        sizePercent = 0.05f,
        buttonResId = R.drawable.upgrade,
        sdlKeyEvent = KeyEvent.KEYCODE_L,
        showInQuickPanel = true,
    ),
    SDL3ImageButton(
        "toggle_soldier_levels",
        EngineTypes.Widelands,
        offsetXPercent = 0.22f,
        offsetYPercent = 0.39f,
        sizePercent = 0.05f,
        buttonResId = R.drawable.upgrade,
        sdlKeyEvent = KeyEvent.KEYCODE_L,
        showInQuickPanel = true,
    ),
    SDL3ImageButton(
        "toggle_building_visibility",
        EngineTypes.Widelands,
        offsetXPercent = 0.28f,
        offsetYPercent = 0.39f,
        sizePercent = 0.05f,
        buttonResId = R.drawable.visibility_lock,
        sdlKeyEvent = KeyEvent.KEYCODE_U,
        showInQuickPanel = true,
    ),
    SDL3ImageButton(
        "toggle_overlapping_workareas",
        EngineTypes.Widelands,
        offsetXPercent = 0.34f,
        offsetYPercent = 0.39f,
        sizePercent = 0.05f,
        buttonResId = R.drawable.donkey,
        sdlKeyEvent = KeyEvent.KEYCODE_W,
        showInQuickPanel = true,
    ),
    SDL3ImageButton(
        "scroll_to_starting_field",
        EngineTypes.Widelands,
        offsetXPercent = 0.40f,
        offsetYPercent = 0.39f,
        sizePercent = 0.05f,
        buttonResId = R.drawable.house,
        sdlKeyEvent = KeyEvent.KEYCODE_MOVE_HOME,
        showInQuickPanel = true,
    ),
    SDL3ImageButton(
        "toggle_quick_navigation",
        EngineTypes.Widelands,
        offsetXPercent = 0.16f,
        offsetYPercent = 0.51f,
        sizePercent = 0.05f,
        buttonResId = R.drawable.navigation,
        sdlKeyEvent = KeyEvent.KEYCODE_V,
        showInQuickPanel = true,
    ),
    SDL3ImageButton(
        "pinned_note",
        EngineTypes.Widelands,
        offsetXPercent = 0.22f,
        offsetYPercent = 0.51f,
        sizePercent = 0.05f,
        buttonResId = R.drawable.scroll_quill,
        sdlKeyEvent = KeyEvent.KEYCODE_F8,
        showInQuickPanel = true,
    ),
    SDL3ImageButton(
        "go_to_location",
        EngineTypes.Widelands,
        offsetXPercent = 0.28f,
        offsetYPercent = 0.51f,
        sizePercent = 0.05f,
        buttonResId = R.drawable.position_marker,
        sdlKeyEvent = KeyEvent.KEYCODE_G,
        showInQuickPanel = true,
    ),
    SDL3ImageButton(
        "go_to_ship",
        EngineTypes.Widelands,
        offsetXPercent = 0.34f,
        offsetYPercent = 0.51f,
        sizePercent = 0.05f,
        buttonResId = R.drawable.sailboat,
        sdlKeyEvent = KeyEvent.KEYCODE_J,
        showInQuickPanel = true,
    ),
    SDL3ImageButton(
        "watch_ship",
        EngineTypes.Widelands,
        offsetXPercent = 0.16f,
        offsetYPercent = 0.63f,
        sizePercent = 0.05f,
        buttonResId = R.drawable.binoculars,
        sdlKeyEvent = KeyEvent.KEYCODE_F,
        showInQuickPanel = true,
    ),
    SDL3ImageButton(
        "open_ship_window",
        EngineTypes.Widelands,
        offsetXPercent = 0.22f,
        offsetYPercent = 0.63f,
        sizePercent = 0.05f,
        buttonResId = R.drawable.ship_wheel,
        sdlKeyEvent = KeyEvent.KEYCODE_O,
        showInQuickPanel = true,
    ),
    SDL3ImageButton(
        "toggle_building_spaces",
        EngineTypes.Widelands,
        offsetXPercent = 0.28f,
        offsetYPercent = 0.63f,
        sizePercent = 0.05f,
        buttonResId = R.drawable.barracks,
        sdlKeyEvent = KeyEvent.KEYCODE_SPACE,
        showInQuickPanel = true,
    ),
    SDL3MouseWheelButton(
        "zoom_in",
        EngineTypes.Widelands,
        wheelUp = true,
        offsetXPercent = 0.85f,
        offsetYPercent = 0.06f,
        sizePercent = 0.055f,
        buttonResId = R.drawable.next_weapon,
        invokeWheelEventsWhilePressingDefaultState = true
    ),
    SDL3MouseWheelButton(
        "zoom_out",
        EngineTypes.Widelands,
        wheelUp = false,
        offsetXPercent = 0.85f,
        offsetYPercent = 0.18f,
        sizePercent = 0.055f,
        buttonResId = R.drawable.prev_weapon,
        invokeWheelEventsWhilePressingDefaultState = true
    ),
    SDL3MouseImageButton(
        "camera_movement_mode",
        EngineTypes.Widelands,
        offsetXPercent = 0.8f,
        offsetYPercent = 0.41f,
        sizePercent = 0.08f,
        buttonResId = R.drawable.magnifying_glass,
        sdlKeyEvent = SDL_BUTTON_RIGHT,
        consumeTouchEventsByDefault = true,
        ignoreOutOfBoundsTouchEvents = false,
        useToggle = true,
        onTouchDownEvent = { screenControls, _ -> screenControls?.apply { isZoomMode = true } },
        onTouchUpEvent = { screenControls, _ -> screenControls?.apply { isZoomMode = false } }
    ),
    SDL3ImageButton(
        "escape",
        EngineTypes.Widelands,
        offsetXPercent = 0.99f,
        offsetYPercent = 0.05f,
        sizePercent = 0.065f,
        buttonResId = R.drawable.pause,
        sdlKeyEvent = KeyEvent.KEYCODE_ESCAPE,
    ),
    SDL3ImageButton(
        "minimap",
        EngineTypes.Widelands,
        offsetXPercent = 0.8f,
        offsetYPercent = 0.85f,
        sizePercent = 0.055f,
        buttonResId = R.drawable.automap,
        sdlKeyEvent = KeyEvent.KEYCODE_M
    ),
    SDL3ImageButton(
        "inventory",
        EngineTypes.Widelands,
        offsetXPercent = 0.94f,
        offsetYPercent = 0.25f,
        sizePercent = 0.055f,
        buttonResId = R.drawable.locked_chest,
        sdlKeyEvent = KeyEvent.KEYCODE_I,
    ),
    ShowSDLKeyboardButton(
        KeyboardType.SDL3Keyboard,
        EngineTypes.Widelands,
        offsetXPercent = 0.75f,
        offsetYPercent = 0.03f,
        sizePercent = 0.08f,
        buttonResId = R.drawable.keyboard,
        useReturnButton = true
    ),
    UpdateScreenControlsVisibilityImageButton(
        EngineTypes.Widelands,
        offsetXPercent = 0.62f,
        offsetYPercent = 0.03f,
        sizePercent = 0.05f,
        buttonResId = R.drawable.toggles,
    ))