name: Android Release Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_NDK_VERSION: r28b
      CMAKE_VERSION: 4.0.2
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk

    steps:
    - name: Checkout code with submodules
        uses: actions/checkout@v4
        with:
        submodules: 'recursive'
        fetch-depth: 0

    - name: Update submodules (fallback)
        if: always()
        run: |
            git submodule sync --recursive
            git submodule update --init --force --recursive --depth=1

    - name: Cache Gradle
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Cache Android SDK
      uses: actions/cache@v3
      with:
        path: ${{ env.ANDROID_SDK_ROOT }}
        key: ${{ runner.os }}-android-sdk-${{ hashFiles('**/build.gradle*') }}-${{ env.ANDROID_NDK_VERSION }}
        restore-keys: |
          ${{ runner.os }}-android-sdk-

    - name: Set up JDK 24
      uses: actions/setup-java@v3
      with:
        java-version: 24
        distribution: 'temurin'

    - name: Install required packages
      run: sudo apt-get -qq install unzip wget

    - name: Setup Android SDK
      if: steps.cache-android-sdk.outputs.cache-hit != 'true'
      run: |
        mkdir -p $ANDROID_SDK_ROOT
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip commandlinetools-linux-*.zip -d $ANDROID_SDK_ROOT/cmdline-tools
        mv $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools/latest
        echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> $GITHUB_PATH

    - name: Install Android SDK components
      if: steps.cache-android-sdk.outputs.cache-hit != 'true'
      run: |
        yes | sdkmanager --licenses
        sdkmanager "platforms;android-36"
        sdkmanager "build-tools;36.0.0"
        sdkmanager "platform-tools"
        sdkmanager "cmdline-tools;latest"
        echo "ANDROID_HOME=$ANDROID_SDK_ROOT" >> $GITHUB_ENV

    # 4. УСТАНОВКА ОСТАЛЬНЫХ КОМПОНЕНТОВ
    - name: Download and setup NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-${{ env.ANDROID_NDK_VERSION }}-linux.zip
        unzip -q android-ndk-*.zip
        echo "ANDROID_NDK_HOME=$GITHUB_WORKSPACE/android-ndk-${{ env.ANDROID_NDK_VERSION }}" >> $GITHUB_ENV

    - name: Download and setup CMake
      run: |
        wget https://github.com/Kitware/CMake/releases/download/v${{ env.CMAKE_VERSION }}/cmake-${{ env.CMAKE_VERSION }}-Linux-x86_64.tar.gz
        tar -xzf cmake-*.tar.gz
        echo "$GITHUB_WORKSPACE/cmake-${{ env.CMAKE_VERSION }}-Linux-x86_64/bin" >> $GITHUB_PATH

    # 5. СБОРКА ПРОЕКТА
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Release with Gradle
      run: ./gradlew assembleRelease --stacktrace
      env:
        ANDROID_NDK: ${{ env.ANDROID_NDK_HOME }}