name: Android Release Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'

    - name: Install required packages
      run: |
        sudo apt-get -qq update
        sudo apt-get -qq install unzip

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Release with Gradle
      run: ./gradlew assembleRelease